---
driver:
  name: vagrant

provisioner:
  name: chef_zero
#  require_chef_omnibus: true
#  chef_omnibus_url: file:///mnt/data_bags/scripts/install.sh
  environments_path: /Users/ongomr/DevOps/chef/envs
  roles_path: /Users/ongomr/DevOps/chef/roles

platforms:
  - name: centos7
    driver:
      customize:
       memory: 2048
       cpus: 2
      box: centos7
      box_url: /Users/ongomr/DevOps/vagrant/boxes/centos7.box
      network:
      - ["private_network", {ip: "192.168.56.84"}]
      synced_folders:
      - ["/Users/ongomr/DevOps/chef/data_bags/lab_data_bags/", "/mnt/data_bags", "disabled: false"]

# Allocation Range started at IP: 192.168.56.100
suites:
  - name: chfsrv
    environment: lab
    driver:
      vm_hostname: chfsrv
      customize:
       memory: 4096
       cpus: 2
      network:
      - ["private_network", {ip: "192.168.56.100"}]
#      - ["public_network", {ip: "192.168.56.100"}]
    run_list:
      - recipe[chefsrv::default]
    excludes:
      -
    attributes:
